### ISSUE TITLE
Consider brand implications

### ISSUE THREAD

**Issue by cassiemc** [mozilla/mozmaker#32]
This may be a non-issue but I want to make sure we consider it. What are the brand implications of unofficial prototypes or community members using the very official-seeming foxlight? Any harm in making unofficial projects look official?

**Comment by sabrinang** [comment]
I'd consider a more generic prefix like "moz" than "fox" as it implies ties to the larger mozilla brand than to the firefox brand.

**Comment by gvn** [comment]
@cassiemc Does this ticket still need to be open now that we renamed it?

**Comment by cassiemc** [comment]
This ticket has nothing to do with the name - really more to do with scenarios where a project that is not officially run by mozilla but looks like it is because it uses mozmaker. I'm not sure if we should release some kind of guidelines.

**Comment by gvn** [comment]
Hmm. Anything we do can be co-opted by anyone and that's really the nature, and potentially double edged sword depending on your viewpoint, of open work.

Telling people outside Mozilla not to use it seems kind of un-Mozilla if that's what you mean.

In practice, I wouldn't personally be too concerned about it. We're not heavily promoting it outside of our internal channels.

**Comment by cassiemc** [comment]
Nope, that's not what I mean. In theory Mozmaker could be accompanied by brand guidelines, or some other mitigation (that's what I want to do this ticket). It's my job to worry about brand! But I have no intentions to be un-mozilla :)

**Comment by cassiemc** [comment]
I'm going to close this but cc @xmatthewx @lovegushwa @simonwex and @hannahkane b/c it's an interesting process problem to wrap heads around. Do we schedule monthly audits of sites/pages shipped with the cms? Do we have a review process prior to being able to publish (solved through permissions)? Do we not care, and embrace the spontaneity of self-publishing? 

Feel free to file followups if it's something you'd like to pursue.

**Comment by hannahkane** [comment]
Thanks, @cassiemc. I think this is an important question that encompasses more than just branding even. I think it might be useful to have a lightweight convention for having all content reviewed before it's published, similar to how code is peer reviewed. We may not need to have permissions around it, just an agreed-upon convention. But I'm thinking more about content in general, so will defer to @lovegushwa and @xmatthewx on the branding question specifically.
