### ISSUE TITLE
Write documentation: How to use Foxlight without the CMS

### ISSUE THREAD

**Issue by hannahkane** [mozilla/mozmaker#37]
We need to figure out and document what our process will be for production team members to make use of Foxlite beyond the CMS

**Comment by simonwex** [comment]
@flukeout do you mind adding words to describe your colour-selection process you want documented?

**Comment by flukeout** [comment]
This applies to uses of Foxlight outside of Calypso, for example, if someone in our network has a vanilla HTML document that they want to style.

To do so, they could include the compiled Foxlight CSS with a ``link`` tag in their HTML document. However, there isn't a way for that author to then specify which of the primary colors in the Foxlight theme / Foundation branding scheme they want to use.

One idea is to allow the author to add classes like ``.foxlight-orange`` or ``foxlight-navy`` that the ``<body>`` tag of their page. This would have the effect of changing the primary color for the whole document.

**Comment by gvn** [comment]
I think this is covered by:
https://github.com/mozilla/mozmaker#usage

Closing...
