### ISSUE TITLE
Discuss the Mozmaker Name

### ISSUE THREAD

**Issue by vazquez** [mozilla/mozmaker#54]
During our Demo call, @davidascher pointed out the significance of choosing a name for contributors and the open-source community. Maybe we haven't hit the mark with `Mozmaker` just yet.

Let's reopen the discussion of the Mozmaker name.

cc: @cassiemc @gvn @flukeout

**Comment by davidascher** [comment]
In particular, let's think about who the audience for the name is, and what
we want the name to convey/imply.  And let's also consider, un-brandy name
(e.g. "mofo-bootstrap4-theme") as potential options.

--da

**Comment by gvn** [comment]
Bear in mind that this is the prefix for several other projects, so a simple 1 word name is best.

EG: `mozmaker-templates`, `mozmaker-font`

I'm not too keen on Mozmaker. Previously we had it as Foxlight, which I am more partial to, but understand the concerns with.

Regardless, it would be great to finalize this name as changing it requires a fair amount of time at this point. :+1:

**Comment by davidascher** [comment]
understand the need for single-word.

foxlight is definitely not acceptable -- it has nothing to do with firefox,
which is a carefully managed brand.

--da

**Comment by gvn** [comment]
Related: https://github.com/mozilla/mozmaker/issues/31

**Comment by gvn** [comment]
Idea: **Leaderhosen**

CC: @simonwex

**Comment by gvn** [comment]
Resolved:

`onesie` is our new name.

**Comment by gvn** [comment]
Hmm, although...

https://en.wikipedia.org/wiki/Onesies_(brand)

> "The terms "Onesie" or "Onesies" are sometimes used in the United States as if they were a genericized trademark;[1][2] however, "Onesies" is a registered trademark of Gerber Childrenswear, which objects to both the usage of the term as a generic name and the usage of the singular form "Onesie".[3][4]"

**Comment by gvn** [comment]
What about **1Z** ?

**Comment by vazquez** [comment]
Or is it 1ZED? :P






On Thu, Mar 17, 2016 at 1:18 PM -0700, "gavin lazar suntop" <notifications@github.com> wrote:












What about 1Z ?

**Comment by gvn** [comment]
I still like `Dapr`.

**Comment by vazquez** [comment]
+1 I like dapr too






On Thu, Mar 17, 2016 at 2:08 PM -0700, "gavin lazar suntop" <notifications@github.com> wrote:












I still like Dapr.

**Comment by simonwex** [comment]
This is the name of a small open source project for use by devs and designers. I'm not worried about copyright infringement. I want to put this to bed. It is called `onesie`.

**Comment by gvn** [comment]
> I want to put this to bed.

Pun intended? ^_^

**Comment by simonwex** [comment]
Sadly no. – Good catch ;)
