### ISSUE TITLE
Make a presentation deck about onesie

### ISSUE THREAD

**Issue by kristinashu** [mozilla/mozmaker#60]
To gather our thoughts and make sure everyone is on the same page, lets make a presentation deck to kick off the onesie conversation.

Some things it could cover:
- why are we doing this? [design audit](https://docs.google.com/a/mozilla.com/presentation/d/13v_Rr2ypxscqSZWksLAzc5TZ8NRy0MuGSP9yK-FEKFo/edit?usp=sharing
- what does it mean?
- what are the limitations? 
- who/what does it effect?
- how and when will it be implemented?

cc @flukeout

**Comment by xmatthewx** [comment]
@kristinashu - thanks for taking the lead on this. 

The deck/conversation could also cover:
 - what's the goal?
 - what are the benefits?
 - what are our options? 

As I see it, the goal of this process: 
 - gain clarity and a sense of shared ownership, so we can enthusiastically, intuitively, and consistently leverage the tool.
 - steer the tool so it's useful for many use cases 
 - optimize it for engineering, design, and audience
 - lead the web toward a better web!

cc @lovegushwa @vazquez @sabrinang @natalieworth

**Comment by kristinashu** [comment]
@xmatthewx can we put this into the next heartbeat? I think a lot of the unifying style work is dependent on it.

**Comment by xmatthewx** [comment]
I filed a planning ticket with a slightly different angle. Let's discuss and edit between now and Monday.

**Comment by kristinashu** [comment]
Closing in lieu of https://github.com/MozillaFoundation/Design/issues/168
